all:cs251.ex1    

cs251.ex1:graphics.o math.o io.o main.o 
	gcc -o cs251.ex1 graphics.o math.o main.o io.o
main.o:main.c common.h
	gcc -c main.c -o main.o
graphics.o:graphics.c math.o common.h
	gcc -c graphics.c -o graphics.o
math.o:math.c common.h
	gcc -c math.c -o math.o
io.o:io.c common.h
	gcc -c io.c -o io.o

clean:
	rm -f *.o cs251.ex1
	
