all:cs251.ex1    
CC=gcc
CFLAGS= -g -I. -DDBG

OBJS = graphics.o math.o io.o main.o

cs251.ex1:$(OBJS)
	$(CC) $(CFLAGS) -o $@ $(OBJS)

$(OBJS) : common.h
graphics.o : math.o
%.o: %.c
	$(CC) -c $(CFLAGS) $< -o $@
clean:
	rm -f *.o cs251.ex1
	
